# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\x04main\"\x17\n\x04Test\x12\x0f\n\x07\x63omment\x18\x01 \x01(\t\"y\n\x07\x45xample\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x15\n\x01t\x18\x03 \x03(\x0b\x32\n.main.Test\x12#\n\x06labels\x18\x04 \x03(\x0b\x32\x13.main.Example.Label\x1a\x17\n\x05Label\x12\x0e\n\x06source\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEST._serialized_start=22
  _TEST._serialized_end=45
  _EXAMPLE._serialized_start=47
  _EXAMPLE._serialized_end=168
  _EXAMPLE_LABEL._serialized_start=145
  _EXAMPLE_LABEL._serialized_end=168
# @@protoc_insertion_point(module_scope)
